services:
  - type: web
    name: cinematch
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: MOVIE_DICT_URL
        sync: false
      - key: SIMILARITY_URL
        sync: false
